### ISSUE TITLE
Live View looks broken

### ISSUE THREAD

**Issue by cnisidis** [vvvv/VL.Devices.DigiCamControl#1]
As you may see bellow, my camera is a Canon 600D (aka Ti3 Rebel)
![image](https://user-images.githubusercontent.com/930194/187798535-4de6f39f-006c-46d8-8bb6-daf95938edf8.png)

**Comment by joreg** [comment]
Interesting. please download latest stable version of digicamcontrol: http://www.digicamcontrol.com/download and see if the liveview works there.

**Comment by cnisidis** [comment]
live view looks correct in digicamcontrol:

![image](https://user-images.githubusercontent.com/930194/187869040-5e746d60-1e42-4ad9-8f2b-a20b6618bd2d.png)

**Comment by joreg** [comment]
good find. i made a change. please try with latest 0.2.1-alpha version of the nuget.

**Comment by cnisidis** [comment]
The latest nuget didn't fix the problem, but I tried out to change the size manually and there is a small difference on what the Camera is providing as the optimal resolution and what actually works. 
In 1056x700 looks perfect, but internally the FocusFrame size is 1036 x 691. Where these pixels went ?

![image](https://user-images.githubusercontent.com/930194/187885653-a283c91e-7e4c-42de-b78f-648f795e1309.png)

and here is what derives from the camera itself

![image](https://user-images.githubusercontent.com/930194/187885851-11eb62dc-adb3-4a2c-8e62-c4037247c2ab.png)

I guess that even a simple switch to add a custom Width/Height would be a nice workaround!

**Comment by joreg** [comment]
ah i see now that LiveViewData also has ImageWidth and ImageHeight properties. can you see if those report the correct values?

**Comment by cnisidis** [comment]
checked that. unfortunately none of these properties is suitable. ImageWidth looks like the full frame (sensor capability ~5184) and the LiveViewImageWidth (and Height respectively) returns always "100". Looks more like a percentage or Thumbnail to me. FocusX and FocusY are returning 2388 and 1741. There is no any obvious correlation to me, among these numbers.

**Comment by joreg** [comment]
ok. i took another approach. please test again with version 0.2.2-alpha of the nuget

**Comment by cnisidis** [comment]
hello @joreg , it looks perfect, version 0.2.2-alpha is working great

![image](https://user-images.githubusercontent.com/930194/188309419-5665225e-9619-430a-96f9-46b84088e167.png)

**Comment by joreg** [comment]
good to hear. thanks for the report and checking!
